version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "examples/**",
  "docs/**"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"